version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  # UI Jenkins
      - "50000:50000" # Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home # Volume for Jenkins .data

volumes:
  jenkins_home:
    driver: local
