version: '3.8'

services:
  jenkins:
    build:
      context: .  # Path where the Dockerfile is located
      dockerfile: Dockerfile  # Name of the Dockerfile
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"  # UI Jenkins
      - "50000:50000" # Jenkins agents
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dcom.sun.net.ssl.checkRevocation=false -Djavax.net.ssl.trustStore=/dev/null
    volumes:
      - jenkins_home:/var/jenkins_home # Volume for Jenkins .data
      - ./init-scripts:/var/jenkins_init_scripts # We mount the init scripts
      - ./jenkins_plugins:/var/jenkins_home/plugins # We mount the plugins
#      - ./hosts/hosts:/etc/hosts  # Custom Hosts file
    entrypoint: ["/bin/bash", "-c", "/var/jenkins_init_scripts/init.sh && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4  # Google DNS

volumes:
  jenkins_home:
    driver: local
