name: Configure Webhook for Jenkins

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        options:
          - dev

jobs:
  configure-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python version to use

      - name: Instalar dependencias
        run: |
          pip install requests python-jenkins

      - name: Execute script to configure webhook
        run: |
          python ./python/main.py
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
